# -*- coding: utf-8 -*-
"""numpy_xndirner

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18nFxlkNECd3lWRuy93UmEfkDzmJInEB2
"""

#XNDIR1
# import numpy as np

# temperatures = np.array([
#     [25, 28, 31, 26, 30, 29, 27],  # City 1
#     [18, 21, 19, 22, 20, 23, 24],  # City 2
#     [32, 35, 33, 31, 34, 36, 37]   # City 3
# ])

# city1_mean = np.mean(temperatures[0])
# city2_mean = np.mean(temperatures[1])
# city3_mean = np.mean(temperatures[2])
# print(f'Mean temperature for City 1: {city1_mean}')
# print(f'Mean temperature for City 2: {city2_mean}')
# print(f'Mean temperature for City 3: {city3_mean}')
# print(f'Max temperature for City 1: {np.max(temperatures[0])}')
# print(f'Max temperature for City 2: {np.max(temperatures[1])}')
# print(f'Max temperature for City 3: {np.max(temperatures[2])}')
# print(f'Coldest temperature for all cities: {np.min(temperatures)} ')

# for i in temperatures:
#   farenhait = []
#   for j in i:
#     j = j * 9/5 +32
#     farenhait.append(j)
#     temperatures_farenhait = np.array(farenhait)
#   print(f'Temperatures in Farenhait: {temperatures_farenhait}',end="\n")

# print(f'Average temperature for all cities combined:{np.average(temperatures)}')

#XNDIR2
import numpy as np
import csv

path = "/sales_data_types.csv"
data = []

with open(path, 'r') as csv_file:
    csv_reader = csv.reader(csv_file)
    for row in csv_reader:
        data.append(row)


numpy_array = np.array(data)

sales_2016 = np.sum([float(row[2].replace('$', '').replace(',', '')) for row in data[1:]]) #2016i mijin
sales_2017 = np.sum([float(row[3].replace('$','').replace(',',''))for row in data[1:]]) #2017i mijin
percent_growth_ave = np.mean([float(row[4].replace('%', '')) for row in data[1:]]) #Percent Growth mijin
growth_rate= (sales_2017 - sales_2016)/sales_2016 * 100 #Calculate the average percentage growth from 2016 to 2017 across all customers.

closed_jan_customers = []
for customer in data[1:]:
    if customer[5] == 'Closed':
        closed_jan_customers.append(customer) #List the customers who have 'Closed' as their January units.


count_jan_customers = []
for row in data[1:]:
  if row[5] == "Closed":
    continue
  else:
    count_jan_customers.append(float(row[5]))
count = sum(count_jan_customers) #Calculate the Total January Units Sold:

active_customers=[]
for active in data[1:]:
  if active[9] == 'Y':
    active_customers.append(float(active[5]))
    whole=sum(active_customers) #January units sold by active customers

max_sales_2017 = np.max([float(row[3].replace('$', '').replace(',', '')) for row in data[1:]]) #Max sales in 2017


print(numpy_array)
print(f"1.Sales_2016 = {sales_2016}")
print(f"  Sales_2017 = {sales_2017}")
print(f"2. Percent_growth_ave = {percent_growth_ave}")
print(f"3. Growth_rate = {growth_rate}")

for customer in closed_jan_customers:
    print(f'4.Closed January Units{customer}')
print(f'5.Count_jan_customers = {count}')
print(f"6.January units sold by active customers = {whole}")
print(f'7.Max sales in 2017 = {max_sales_2017}')