# -*- coding: utf-8 -*-
"""pandas_xndir

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rpUK7Xna4CerkYf2CItTTosFr92C9eys
"""

import pandas as pd
import csv
import numpy as np


data1 = [
    {"customer_id": 1, "name": "Alice Johnson", "email": "alice@example.com", "signup_date": "2023-01-15"},
    {"customer_id": 2, "name": "Bob Smith", "email": "bob@example.com", "signup_date": "2023-02-20"},
    {"customer_id": 3, "name": "Charlie Brown", "email": "charlie@example.com", "signup_date": "2023-03-10"},
]


data2 = [
    {"order_id": 101, "customer_id": 1, "order_date": "2023-05-10", "total_amount": 200.50},
    {"order_id": 102, "customer_id": 1, "order_date": "2023-06-12", "total_amount": 150.75},
    {"order_id": 103, "customer_id": 2, "order_date": "2023-07-05", "total_amount": 300.40},
    {"order_id": 104, "customer_id": 3, "order_date": "2023-08-14", "total_amount": 250.90},
    {"order_id": 105, "customer_id": 2, "order_date": "2023-09-10", "total_amount": 120.00},
    {"order_id": 106, "customer_id": 1, "order_date": "2023-10-01", "total_amount": 180.30},
]


customers_df = pd.DataFrame(data1, columns=["customer_id", "name", "email", "signup_date"])
customers_df = customers_df.set_index("customer_id")
print(customers_df,"\n")


orders_df = pd.DataFrame(data2, columns=["order_id", "customer_id", "order_date", "total_amount"])
orders_df = orders_df.set_index("order_id")
print(orders_df)
#Find the total number of customers and the total number of orders.
count_customers =list(customers_df.index)
count_orders = list(orders_df.index)
total_customers = len(count_customers)
total_orders = len(count_orders)
print(f"Total number of customers: {total_customers}")

print(f"Total number of orders: {total_orders}")

#Calculate the total revenue
total = orders_df["total_amount"].sum()
print(f"Total revenue: ${total:.2f}")
total_revenue =orders_df.groupby("customer_id")["total_amount"].sum()
print(total_revenue)

#Find the highest-spending customer
highest_spending_customer_id = total_revenue.idxmax()
highest_spending_customer = customers_df.loc[highest_spending_customer_id, "name"]
print(f"Highest-spending customer: {highest_spending_customer}")

#Find the month with the highest total sales
orders_df['year_month'] = orders_df['order_date'].str[:7]
monthly_sales = orders_df.groupby('year_month')['total_amount'].sum()
highest_sales_month = monthly_sales.idxmax()
print(f"Month with the highest total sales: {highest_sales_month}")

# Save summary and top customers to a CSV file
summary_data = {
    "Total Customers": [total_customers],  # Use total count, not list
    "Total Orders": [total_orders],
    "Total Revenue": [total_revenue],
    "Highest Sales Month": [highest_sales_month],
}

# Create DataFrame and save as CSV
summary_df = pd.DataFrame(summary_data)
summary_df.to_csv("sales_summary.csv", index=False)
print("Sales summary saved as 'sales_summary.csv'.")